<!-- Generated by scripts/gen_frontend.py. Edit that, not this file. -->
<template>
  <!-- `side` + `align`, not `placement`: frappe-ui removed `placement` in 1.0
       and warns about it in dev, so the menu was never positioned. -->
  <Dropdown :options="options" side="top" align="start" class="w-full">
    <!-- icon-right, not a #suffix holding an <Icon>: Button declares the prop
         and renders it at the library's own size and tone. The #prefix stays a
         slot because an Avatar is not something an icon prop can express. -->
    <!--
      Collapsed, the column is 3rem and a name is not something 3rem can hold:
      it does not truncate to nothing, it runs out of the column and off the
      edge of the window. So the trigger becomes the avatar it already had.

      `!gap-0` as well as centring, because Button lays out prefix, label and
      suffix with a gap and still renders the label span when the slot inside
      it draws nothing. An empty span plus 8px of gap is 8px of nothing after
      the avatar, and a centred row of two things one of which is invisible
      puts the visible one four pixels off the line everything else sits on.
    -->
    <Button
      variant="ghost"
      :icon-right="compact ? undefined : 'lucide-chevron-up'"
      class="!h-11 w-full"
      :class="compact ? '!justify-center !gap-0 !px-0' : '!justify-start !px-2'"
      :label="displayName"
    >
      <template #prefix>
        <Avatar :label="displayName" :image="avatar" size="md" />
      </template>
      <span v-if="!compact" class="min-w-0 flex-1 text-start">
        <span class="block truncate text-base text-ink-gray-8">{{ displayName }}</span>
        <span v-if="subtitle" class="block truncate text-xs text-ink-gray-5">
          {{ subtitle }}
        </span>
      </span>
    </Button>
  </Dropdown>
</template>

<script setup>
import { computed } from 'vue'
import { Avatar, Button, Dropdown } from '@/ui'
import { useAppearance } from '@/lib/shell/appearance'
import { signOut } from '@/lib/shell/user'
import { __ } from '@/lib/runtime/translate'

const props = defineProps({
  name: { type: String, default: '' },
  email: { type: String, default: '' },
  avatar: { type: String, default: '' },
  subtitle: { type: String, default: '' },
  // Entries shown above the standard ones, e.g. Settings for an operator.
  extra: { type: Array, default: () => [] },
  /** The avatar alone, for a column folded to its icons. */
  compact: { type: Boolean, default: false },
})

const displayName = computed(() => props.name || props.email || __('Account'))

// Appearance sits here as well as in settings: it is the preference people
// change most often, and hunting for it behind a dialog is the slow path.
//
// Three rows in a group rather than a switch. A two-state control cannot
// express "follow the system", so anyone who wants that ends up flipping it by
// hand twice a day — and a row is the same single tap a switch would be, with
// the current choice visible instead of inferred. `selected` is a
// MenuBaseOption field, so the tick is the library's own.
const { menuGroup } = useAppearance()

const options = computed(() => [
  ...props.extra,
  menuGroup.value,
  {
    label: __('Log out'),
    icon: 'lucide-log-out',
    onClick: signOut,
  },
])
</script>
