// Generated by scripts/gen_brand.py from scripts/brand/marks.source.html.
// Edit the page, run the script. Do not edit this file.

/**
 * The app marks, as SVG bodies.
 *
 * `body` is what goes inside a `<svg viewBox="0 0 100 100">` — defs,
 * masks and shapes. Every id it declares carries a __ONE__ token which
 * `BrandMark.vue` replaces with something unique per instance: two copies
 * of one mark on a page would otherwise be two elements with one id, and
 * unmounting either takes the gradient the other is pointing at.
 *
 * `colour` is the mark's own, for the rare surface that needs the hue
 * without the drawing — a dot beside a name, a chart series.
 */
export const UNIQUE = "__ONE__"

export const MARKS = {
  "one": {
    name: "One",
    colour: "#4f46e5",
    said: "The platform",
    body: "<defs>\n    <linearGradient id=\"hdr-grad__ONE__\" x1=\"0%\" y1=\"0%\" x2=\"100%\" y2=\"100%\">\n      <stop offset=\"0%\" stop-color=\"#818cf8\"/>\n      <stop offset=\"100%\" stop-color=\"#4f46e5\"/>\n    </linearGradient>\n  </defs>\n  <path d=\"M 28 36 L 46 18 L 46 36 Z\" fill=\"url(#hdr-grad__ONE__)\"/>\n  <mask id=\"hdr-parent-mask__ONE__\">\n    <rect width=\"100%\" height=\"100%\" fill=\"#fff\" />\n    <line x1=\"53\" y1=\"18\" x2=\"53\" y2=\"82\" stroke=\"#000\" stroke-width=\"3\"/>\n    <line x1=\"60\" y1=\"18\" x2=\"60\" y2=\"82\" stroke=\"#000\" stroke-width=\"2.5\"/>\n  </mask>\n  <path d=\"M 46 18 L 66 18 L 66 82 L 46 82 Z\" fill=\"var(--brand-knockout, #ffffff)\" mask=\"url(#hdr-parent-mask__ONE__)\"/>",
  },
  "onespace": {
    name: "OneSpace",
    colour: "#6366f1",
    said: "Unified Workspace & Accounts Gateway",
    body: "<defs>\n  <linearGradient id=\"g-onespace__ONE__\" x1=\"0%\" y1=\"0%\" x2=\"100%\" y2=\"100%\">\n    <stop offset=\"0%\" stop-color=\"#818cf8\"/>\n    <stop offset=\"100%\" stop-color=\"#4338ca\"/>\n  </linearGradient>\n  </defs>\n<!-- Gateway Orbit Ring -->\n<circle cx=\"50\" cy=\"50\" r=\"34\" fill=\"none\" stroke=\"url(#g-onespace__ONE__)\" stroke-width=\"12\" />\n<!-- Purposeful White Core Nexus -->\n<circle cx=\"50\" cy=\"50\" r=\"12\" fill=\"var(--brand-knockout, #ffffff)\" />",
  },
  "oneadmin": {
    name: "OneAdmin",
    colour: "#ec4899",
    said: "Control Plane, IAM & Governance",
    body: "<defs>\n  <linearGradient id=\"g-oneadmin__ONE__\" x1=\"0%\" y1=\"0%\" x2=\"100%\" y2=\"100%\">\n    <stop offset=\"0%\" stop-color=\"#f472b6\"/>\n    <stop offset=\"100%\" stop-color=\"#db2777\"/>\n  </linearGradient>\n  </defs>\n<!-- Governor Dial -->\n<path d=\"M 43 14 L 57 14 L 59 23 L 69 27 L 77 21 L 84 28 L 79 36 L 83 46 L 92 48 L 92 62 L 83 64 L 79 74 L 84 82 L 77 89 L 69 83 L 59 87 L 43 87 L 41 78 L 31 74 L 23 80 L 16 73 L 21 65 L 17 55 L 8 53 L 8 39 L 17 37 L 21 27 L 16 20 L 23 13 L 31 19 Z\" fill=\"url(#g-oneadmin__ONE__)\"/>\n<!-- White Hub Axle -->\n<circle cx=\"50\" cy=\"50\" r=\"16\" fill=\"none\" stroke=\"var(--brand-knockout, #ffffff)\" stroke-width=\"4\" />",
  },
  "oneinventory": {
    name: "OneInventory",
    colour: "#06b6d4",
    said: "Logistics, SKU Barcodes & Warehouse Stock",
    body: "<defs>\n  <linearGradient id=\"g-oneinventory__ONE__\" x1=\"0%\" y1=\"0%\" x2=\"100%\" y2=\"100%\">\n    <stop offset=\"0%\" stop-color=\"#22d3ee\"/>\n    <stop offset=\"100%\" stop-color=\"#0284c7\"/>\n  </linearGradient>\n  <mask id=\"m-oneinventory__ONE__\">\n    <rect width=\"100%\" height=\"100%\" fill=\"#ffffff\" />\n    <line x1=\"38\" y1=\"15\" x2=\"38\" y2=\"85\" stroke=\"#000000\" stroke-width=\"3\" />\n    <line x1=\"43\" y1=\"15\" x2=\"43\" y2=\"85\" stroke=\"#000000\" stroke-width=\"1.5\" />\n    <line x1=\"47\" y1=\"15\" x2=\"47\" y2=\"85\" stroke=\"#000000\" stroke-width=\"3.5\" />\n    <line x1=\"53\" y1=\"15\" x2=\"53\" y2=\"85\" stroke=\"#000000\" stroke-width=\"1.8\" />\n    <line x1=\"58\" y1=\"15\" x2=\"58\" y2=\"85\" stroke=\"#000000\" stroke-width=\"4\" />\n    <line x1=\"63\" y1=\"15\" x2=\"63\" y2=\"85\" stroke=\"#000000\" stroke-width=\"2\" />\n  </mask>\n</defs>\n<!-- Cargo Container Crate -->\n<rect x=\"22\" y=\"18\" width=\"56\" height=\"48\" rx=\"6\" fill=\"url(#g-oneinventory__ONE__)\" mask=\"url(#m-oneinventory__ONE__)\"/>\n<!-- Semantic White Pallet Base -->\n<rect x=\"20\" y=\"70\" width=\"60\" height=\"10\" rx=\"2\" fill=\"var(--brand-knockout, #ffffff)\" mask=\"url(#m-oneinventory__ONE__)\"/>",
  },
  "onewallet": {
    name: "OneWallet",
    colour: "#10b981",
    said: "Digital Card & Balance Ledger",
    body: "<defs>\n  <linearGradient id=\"g-onewallet__ONE__\" x1=\"0%\" y1=\"0%\" x2=\"100%\" y2=\"100%\">\n    <stop offset=\"0%\" stop-color=\"#34d399\"/>\n    <stop offset=\"100%\" stop-color=\"#059669\"/>\n  </linearGradient>\n  </defs>\n<!-- Green Card Body -->\n<rect x=\"18\" y=\"26\" width=\"64\" height=\"48\" rx=\"8\" fill=\"url(#g-onewallet__ONE__)\"/>\n<!-- White Smart EMV Chip -->\n<rect x=\"28\" y=\"42\" width=\"14\" height=\"16\" rx=\"3\" fill=\"var(--brand-knockout, #ffffff)\"/>",
  },
  "onecredit": {
    name: "OneCredit",
    colour: "#f59e0b",
    said: "In-App Token & Platform Currency Symbol",
    body: "<defs>\n  <linearGradient id=\"g-onecredit__ONE__\" x1=\"0%\" y1=\"0%\" x2=\"100%\" y2=\"100%\">\n    <stop offset=\"0%\" stop-color=\"#fbbf24\"/>\n    <stop offset=\"100%\" stop-color=\"#d97706\"/>\n  </linearGradient>\n</defs>\n<!-- Token Ring Coin -->\n<circle cx=\"50\" cy=\"50\" r=\"34\" fill=\"url(#g-onecredit__ONE__)\" />\n<circle cx=\"50\" cy=\"50\" r=\"24\" fill=\"var(--brand-ground, #0b0f19)\" />\n<!-- White Central Currency Pillar (Padded inside, not touching edges) -->\n<rect x=\"46\" y=\"31\" width=\"8\" height=\"38\" rx=\"2\" fill=\"var(--brand-knockout, #ffffff)\" />\n<!-- Currency Crossbars Strike (=) -->\n<rect x=\"35\" y=\"43\" width=\"30\" height=\"4\" rx=\"2\" fill=\"url(#g-onecredit__ONE__)\" />\n<rect x=\"35\" y=\"53\" width=\"30\" height=\"4\" rx=\"2\" fill=\"url(#g-onecredit__ONE__)\" />",
  },
  "onemobility": {
    name: "OneMobility",
    colour: "#0284c7",
    said: "Transit Telemetry, Schedules & Routing",
    body: "<defs>\n  <linearGradient id=\"g-onemobility__ONE__\" x1=\"0%\" y1=\"0%\" x2=\"100%\" y2=\"100%\">\n    <stop offset=\"0%\" stop-color=\"#38bdf8\"/>\n    <stop offset=\"100%\" stop-color=\"#0369a1\"/>\n  </linearGradient>\n  </defs>\n<!-- Route Waypoint Diamond -->\n<rect x=\"23\" y=\"23\" width=\"54\" height=\"54\" rx=\"10\" transform=\"rotate(45 50 50)\" fill=\"url(#g-onemobility__ONE__)\"/>\n<!-- White Interchange Hub -->\n<circle cx=\"50\" cy=\"50\" r=\"10\" fill=\"var(--brand-knockout, #ffffff)\"/>",
  },
  "onearchive": {
    name: "OneArchive",
    colour: "#64748b",
    said: "Intelligent Long-Term Cold Storage & Vault",
    body: "<defs>\n  <linearGradient id=\"g-onearchive__ONE__\" x1=\"0%\" y1=\"0%\" x2=\"100%\" y2=\"100%\">\n    <stop offset=\"0%\" stop-color=\"#94a3b8\"/>\n    <stop offset=\"100%\" stop-color=\"#475569\"/>\n  </linearGradient>\n  </defs>\n<!-- White Document Folder Tab Peeking Out -->\n<path d=\"M 28 26 L 50 26 L 56 32 L 72 32 C 75 32 76 34 76 37 L 76 56 L 24 56 L 24 30 C 24 28 26 26 28 26 Z\" fill=\"var(--brand-knockout, #ffffff)\"/>\n<!-- Steel Storage Drawer -->\n<rect x=\"18\" y=\"42\" width=\"64\" height=\"40\" rx=\"5\" fill=\"url(#g-onearchive__ONE__)\"/>",
  },
  "onestorage": {
    name: "OneStorage",
    colour: "#0284c7",
    said: "Cloud File Drive & Object Bucket",
    body: "<defs>\n  <linearGradient id=\"g-onestorage__ONE__\" x1=\"0%\" y1=\"0%\" x2=\"100%\" y2=\"100%\">\n    <stop offset=\"0%\" stop-color=\"#38bdf8\"/>\n    <stop offset=\"100%\" stop-color=\"#0284c7\"/>\n  </linearGradient>\n  </defs>\n<!-- Top Storage Blade -->\n<rect x=\"20\" y=\"22\" width=\"60\" height=\"14\" rx=\"4\" fill=\"url(#g-onestorage__ONE__)\"/>\n<!-- Middle Storage Blade with White NVMe Core -->\n<rect x=\"20\" y=\"42\" width=\"60\" height=\"16\" rx=\"4\" fill=\"url(#g-onestorage__ONE__)\"/>\n<rect x=\"36\" y=\"45\" width=\"28\" height=\"10\" rx=\"2\" fill=\"var(--brand-knockout, #ffffff)\"/>\n<!-- Bottom Storage Blade -->\n<rect x=\"20\" y=\"64\" width=\"60\" height=\"14\" rx=\"4\" fill=\"url(#g-onestorage__ONE__)\"/>",
  },
  "onedisplay": {
    name: "OneDisplay",
    colour: "#2563eb",
    said: "Digital Signage & Video Wall Management",
    body: "<defs>\n  <linearGradient id=\"g-onedisplay__ONE__\" x1=\"0%\" y1=\"0%\" x2=\"100%\" y2=\"100%\">\n    <stop offset=\"0%\" stop-color=\"#60a5fa\"/>\n    <stop offset=\"100%\" stop-color=\"#1d4ed8\"/>\n  </linearGradient>\n  </defs>\n<!-- 16:9 Display Screen (Masked) -->\n<rect x=\"16\" y=\"22\" width=\"68\" height=\"44\" rx=\"5\" fill=\"url(#g-onedisplay__ONE__)\"/>\n<!-- Solid White Stand (Completely Uncut) -->\n<path d=\"M 44 66 L 56 66 L 58 76 L 68 76 L 68 80 L 32 80 L 32 76 L 42 76 Z\" fill=\"var(--brand-knockout, #ffffff)\"/>",
  },
  "onesheet": {
    name: "OneSheet",
    colour: "#16a34a",
    said: "Data Tables, Spreadsheets & Financial Models",
    body: "<defs>\n  <linearGradient id=\"g-onesheet__ONE__\" x1=\"0%\" y1=\"0%\" x2=\"100%\" y2=\"100%\">\n    <stop offset=\"0%\" stop-color=\"#4ade80\"/>\n    <stop offset=\"100%\" stop-color=\"#15803d\"/>\n  </linearGradient>\n  </defs>\n<!-- Full White Spreadsheet Grid Body -->\n<rect x=\"18\" y=\"18\" width=\"64\" height=\"64\" rx=\"8\" fill=\"var(--brand-knockout, #ffffff)\"/>\n<!-- Emerald Header Row (Top Section y: 18 to 36) -->\n<path d=\"M 18 26 C 18 21.5 21.5 18 26 18 L 74 18 C 78.5 18 82 21.5 82 26 L 82 36 L 18 36 Z\" fill=\"url(#g-onesheet__ONE__)\"/>",
  },
  "onedoc": {
    name: "OneDoc",
    colour: "#2563eb",
    said: "Collaborative Docs, Notes & Knowledge Base",
    body: "<defs>\n  <linearGradient id=\"g-onedoc__ONE__\" x1=\"0%\" y1=\"0%\" x2=\"100%\" y2=\"100%\">\n    <stop offset=\"0%\" stop-color=\"#60a5fa\"/>\n    <stop offset=\"100%\" stop-color=\"#1d4ed8\"/>\n  </linearGradient>\n  </defs>\n<!-- Blue Document Page Body -->\n<path d=\"M 22 18 L 56 18 L 78 40 L 78 82 L 22 82 Z\" fill=\"url(#g-onedoc__ONE__)\"/>\n<!-- White Folded Corner -->\n<polygon points=\"56,18 56,40 78,40\" fill=\"var(--brand-knockout, #ffffff)\"/>",
  },
  "onehr": {
    name: "OneHR",
    colour: "#f97316",
    said: "People, Teams & Organizational Culture",
    body: "<defs>\n  <linearGradient id=\"g-onehr__ONE__\" x1=\"0%\" y1=\"0%\" x2=\"100%\" y2=\"100%\">\n    <stop offset=\"0%\" stop-color=\"#fb923c\"/>\n    <stop offset=\"100%\" stop-color=\"#ea580c\"/>\n  </linearGradient>\n  </defs>\n<!-- Connecting Synergy Bridge Framework -->\n<path d=\"M 50 30 L 28 66 L 72 66 Z\" fill=\"none\" stroke=\"url(#g-onehr__ONE__)\" stroke-width=\"8\" stroke-linejoin=\"round\"/>\n<!-- Base Peer Talent Nodes (Gradient) -->\n<circle cx=\"28\" cy=\"66\" r=\"12\" fill=\"url(#g-onehr__ONE__)\"/>\n<circle cx=\"72\" cy=\"66\" r=\"12\" fill=\"url(#g-onehr__ONE__)\"/>\n<!-- Keystone Apex Talent Node (White, Sliced by Twin Cuts) -->\n<circle cx=\"50\" cy=\"30\" r=\"13\" fill=\"var(--brand-knockout, #ffffff)\"/>",
  },
  "onebook": {
    name: "OneBook",
    colour: "#e11d48",
    said: "Accounting, Ledgers & Invoicing",
    body: "<defs>\n  <linearGradient id=\"g-onebook__ONE__\" x1=\"0%\" y1=\"0%\" x2=\"100%\" y2=\"100%\">\n    <stop offset=\"0%\" stop-color=\"#fb7185\"/>\n    <stop offset=\"100%\" stop-color=\"#be123c\"/>\n  </linearGradient>\n  </defs>\n<!-- Crimson Hardcover Binding -->\n<path d=\"M 18 28 C 32 24 44 28 50 32 C 56 28 68 24 82 28 L 82 76 C 68 72 56 76 50 80 C 44 76 32 72 18 76 Z\" fill=\"url(#g-onebook__ONE__)\"/>\n<!-- White Ledger Pages Block -->\n<path d=\"M 24 34 C 34 31 44 34 50 38 C 56 34 66 31 76 34 L 76 68 C 66 65 56 68 50 72 C 44 68 34 65 24 68 Z\" fill=\"var(--brand-knockout, #ffffff)\"/>",
  },
  "onecrm": {
    name: "OneCRM",
    colour: "#a855f7",
    said: "Customer Journeys & Relationship Pipeline",
    body: "<defs>\n  <linearGradient id=\"g-onecrm__ONE__\" x1=\"0%\" y1=\"0%\" x2=\"100%\" y2=\"100%\">\n    <stop offset=\"0%\" stop-color=\"#c084fc\"/>\n    <stop offset=\"100%\" stop-color=\"#7e22ce\"/>\n  </linearGradient>\n  </defs>\n<!-- Purple Pipeline Funnel -->\n<polygon points=\"18,22 82,22 58,56 58,82 42,74 42,56\" fill=\"url(#g-onecrm__ONE__)\"/>\n<!-- White Lead Stream Vector -->\n<circle cx=\"50\" cy=\"38\" r=\"8\" fill=\"var(--brand-knockout, #ffffff)\"/>",
  },
  "oneai": {
    name: "OneAI",
    colour: "#f43f5e",
    said: "Intelligence, Neural Models & Automation",
    body: "<defs>\n  <linearGradient id=\"g-oneai__ONE__\" x1=\"0%\" y1=\"0%\" x2=\"100%\" y2=\"100%\">\n    <stop offset=\"0%\" stop-color=\"#fda4af\"/>\n    <stop offset=\"100%\" stop-color=\"#e11d48\"/>\n  </linearGradient>\n  </defs>\n<!-- 4-Point Cognitive Star -->\n<path d=\"M 50 14 C 50 36 36 50 14 50 C 36 50 50 64 50 86 C 50 64 64 50 86 50 C 64 50 50 36 50 14 Z\" fill=\"url(#g-oneai__ONE__)\"/>\n<!-- White Synapse Spark -->\n<circle cx=\"50\" cy=\"50\" r=\"8\" fill=\"var(--brand-knockout, #ffffff)\"/>",
  },
  "onemarket": {
    name: "OneMarket",
    colour: "#14b8a6",
    said: "The marketplace of spaces",
    body: "<defs>\n  <linearGradient id=\"g-onemarket-top__ONE__\" x1=\"0%\" y1=\"0%\" x2=\"100%\" y2=\"100%\">\n    <stop offset=\"0%\" stop-color=\"#5eead4\"/>\n    <stop offset=\"100%\" stop-color=\"#14b8a6\"/>\n  </linearGradient>\n  <linearGradient id=\"g-onemarket-left__ONE__\" x1=\"0%\" y1=\"0%\" x2=\"100%\" y2=\"100%\">\n    <stop offset=\"0%\" stop-color=\"#0f766e\"/>\n    <stop offset=\"100%\" stop-color=\"#115e59\"/>\n  </linearGradient>\n  <linearGradient id=\"g-onemarket-right__ONE__\" x1=\"0%\" y1=\"0%\" x2=\"100%\" y2=\"100%\">\n    <stop offset=\"0%\" stop-color=\"#14b8a6\"/>\n    <stop offset=\"100%\" stop-color=\"#0d9488\"/>\n  </linearGradient>\n  </defs>\n<!-- Isometric Platform Cube - Top Face (Teal Gradient) -->\n<polygon points=\"50,16 82,34 50,52 18,34\" fill=\"url(#g-onemarket-top__ONE__)\" />\n<!-- Upper Surface Center Facet (Only area between cutouts is pure white) -->\n<polygon points=\"43,19.9 50,16 57,19.9 57,48.1 50,52 43,48.1\" fill=\"var(--brand-knockout, #ffffff)\" />\n<!-- Isometric Platform Cube - Left Face (Teal Gradient) -->\n<polygon points=\"18,34 50,52 50,86 18,68\" fill=\"url(#g-onemarket-left__ONE__)\" />\n<!-- Isometric Platform Cube - Right Face (Teal Gradient) -->\n<polygon points=\"50,52 82,34 82,68 50,86\" fill=\"url(#g-onemarket-right__ONE__)\" />",
  },
  "onemail": {
    name: "OneMail",
    colour: "#dc2626",
    said: "The workspace inbox",
    body: "<defs>\n  <linearGradient id=\"g-onemail-back__ONE__\" x1=\"0%\" y1=\"0%\" x2=\"100%\" y2=\"100%\">\n    <stop offset=\"0%\" stop-color=\"#b91c1c\"/>\n    <stop offset=\"100%\" stop-color=\"#7f1d1d\"/>\n  </linearGradient>\n  <linearGradient id=\"g-onemail-pocket__ONE__\" x1=\"0%\" y1=\"0%\" x2=\"100%\" y2=\"100%\">\n    <stop offset=\"0%\" stop-color=\"#f87171\"/>\n    <stop offset=\"100%\" stop-color=\"#dc2626\"/>\n  </linearGradient>\n  </defs>\n<!-- Envelope Interior Shell (Dark Crimson Depth) -->\n<rect x=\"18\" y=\"32\" width=\"64\" height=\"48\" rx=\"6\" fill=\"url(#g-onemail-back__ONE__)\" />\n<!-- Purposeful White Letter Sheet (Rising out of envelope) -->\n<path d=\"M 26 18 L 74 18 C 76.5 18 78 19.5 78 22 L 78 54 L 22 54 L 22 22 C 22 19.5 23.5 18 26 18 Z\" fill=\"var(--brand-knockout, #ffffff)\" />\n<!-- Letter Content Subtle Text Line Hints -->\n<line x1=\"28\" y1=\"26\" x2=\"40\" y2=\"26\" stroke=\"#cbd5e1\" stroke-width=\"2.5\" stroke-linecap=\"round\" />\n<line x1=\"60\" y1=\"26\" x2=\"72\" y2=\"26\" stroke=\"#cbd5e1\" stroke-width=\"2.5\" stroke-linecap=\"round\" />\n<!-- Envelope Front Pocket (V-Fold Shield) -->\n<path d=\"M 18 42 L 50 64 L 82 42 L 82 74 C 82 77.5 79.5 80 76 80 L 24 80 C 20.5 80 18 77.5 18 74 Z\" fill=\"url(#g-onemail-pocket__ONE__)\" />",
  },
  "onecalendar": {
    name: "OneCalendar",
    colour: "#2563eb",
    said: "The week, merged",
    body: "<defs>\n  <linearGradient id=\"g-onecal-header__ONE__\" x1=\"0%\" y1=\"0%\" x2=\"100%\" y2=\"100%\">\n    <stop offset=\"0%\" stop-color=\"#60a5fa\"/>\n    <stop offset=\"100%\" stop-color=\"#2563eb\"/>\n  </linearGradient>\n  <linearGradient id=\"g-onecal-grid__ONE__\" x1=\"0%\" y1=\"0%\" x2=\"100%\" y2=\"100%\">\n    <stop offset=\"0%\" stop-color=\"#1d4ed8\"/>\n    <stop offset=\"100%\" stop-color=\"#1e3a8a\"/>\n  </linearGradient>\n  </defs>\n<!-- Calendar Pad Base (Grid Body) -->\n<rect x=\"18\" y=\"22\" width=\"64\" height=\"64\" rx=\"8\" fill=\"url(#g-onecal-grid__ONE__)\" />\n<!-- Purposeful White Date Sheet Card (Central focal day) -->\n<rect x=\"22\" y=\"38\" width=\"56\" height=\"44\" rx=\"4\" fill=\"var(--brand-knockout, #ffffff)\" />\n<!-- Blue Calendar Month Header Bar -->\n<path d=\"M 18 28 C 18 24.5 20.5 22 24 22 L 76 22 C 79.5 22 82 24.5 82 28 L 82 38 L 18 38 Z\" fill=\"url(#g-onecal-header__ONE__)\" />\n<!-- Dual Binder Ring Clips (Anchor alignment for cuts) -->\n<rect x=\"30\" y=\"14\" width=\"6\" height=\"14\" rx=\"3\" fill=\"var(--brand-knockout, #ffffff)\" />\n<rect x=\"64\" y=\"14\" width=\"6\" height=\"14\" rx=\"3\" fill=\"var(--brand-knockout, #ffffff)\" />",
  },
}

/** Every mark's id, in the order the design lists them. */
export const MARK_NAMES = Object.keys(MARKS)
