// Generated by scripts/gen_frontend.py. Edit that, not this file.

/**
 * A settings panel's own geometry, below frappe-ui's `sm` breakpoint.
 *
 * These were four more, and the four were about the *dialog*: a vertical nav
 * capped at 38vh reflowed into a scrolling strip, a panel column that refused
 * to shrink below its widest table. The dialog is gone — the panels are tabs
 * on the Configuration page now, which has its own tab strip and its own
 * column — so those four went with it.
 *
 * What is left is about the panels themselves, which are still built out of
 * frappe-ui's `SettingsHeader` and `SettingsBody`. Both hard-code
 * `px-[4.4rem]`, which leaves 249px of a 390px screen and wraps "API host" one
 * word per line; and neither ships a footer, so the row Save lives in is the
 * family's missing third piece.
 *
 * They are fallthrough classes on the library's own components rather than a
 * stylesheet override, so nothing here depends on a class name frappe-ui did
 * not publish, and `max-sm:` is the breakpoint those paddings switch at — one
 * number, not two that can disagree.
 *
 * `tests/test_settings_panel_geometry.py` pins the upstream values these
 * compensate for; when frappe-ui makes them responsive, that test fails and
 * this module should go.
 */

/** A panel's pinned header. */
export const PANEL_HEADER = 'max-sm:!px-4 max-sm:!pt-5'

/**
 * A panel's scrolling body. The padding lives on the ScrollArea viewport, which
 * SettingsBody hardcodes, so it is reached through the viewport's data-slot
 * rather than by a class on the component.
 */
export const PANEL_BODY = [
  'max-sm:[&_[data-slot=scroll-area-viewport]]:!px-4',
  'max-sm:[&_[data-slot=scroll-area-viewport]]:!pb-6',
].join(' ')

/**
 * A panel's pinned footer — the row Save lives in.
 *
 * A panel is a flex column of [header, body, footer] and SettingsBody takes
 * `flex-1`, so a sibling placed after it pins to the bottom with no
 * positioning of its own. It has to be there rather than inside the body: a
 * Save button in the scroll region is off-screen on a phone exactly when the
 * form is long enough to need saving. frappe-ui ships SettingsHeader and
 * SettingsBody but no footer, so this is the family's missing third piece.
 */
export const PANEL_FOOTER = [
  'flex shrink-0 items-center gap-2',
  'border-t border-outline-gray-1 bg-surface-elevation-1',
  'px-4 py-3 sm:px-[4.4rem]',
].join(' ')
