// Generated by scripts/gen_catalogue.py from apps/oneapp/oneapp/catalogue.py.
// Do not edit: what an app is, is decided on the server.

export const SPACE = "space"
export const SERVICE = "service"
export const ENGINE = "engine"

/** What each mark is, and whether it exists yet. */
export const KINDS = {
  one: { kind: "engine", built: true },
  onemail: { kind: "service", built: true },
  onecalendar: { kind: "service", built: true },
  onestorage: { kind: "service", built: true },
  onedoc: { kind: "service", built: true },
  onesheet: { kind: "service", built: true },
  onecode: { kind: "service", built: true },
  onetask: { kind: "service", built: true },
  oneai: { kind: "service", built: true },
  onemarket: { kind: "service", built: true },
  onelegal: { kind: "service", built: true },
  onecrm: { kind: "space", built: true },
  onemobility: { kind: "space", built: true },
  onehr: { kind: "space", built: true },
  oneproject: { kind: "space", built: true },
  onebook: { kind: "space", built: true },
  oneinventory: { kind: "space", built: true },
  oneadmin: { kind: "space", built: true },
  onescratchpad: { kind: "service", built: false },
  oneforms: { kind: "service", built: false },
  oneslide: { kind: "service", built: false },
  onesignature: { kind: "service", built: false },
  onedb: { kind: "service", built: false },
  oneticket: { kind: "space", built: false },
  onedisplay: { kind: "space", built: false },
  onegovernance: { kind: "space", built: false },
  onefit: { kind: "space", built: false },
  onestudy: { kind: "space", built: false },
}
