<!-- Generated by scripts/gen_frontend.py. Edit that, not this file. -->
<template>
  <!--
    SettingsRow + Select, which is what SettingsRow is for: a label and a
    description on the left, one compact control on the right.

    Not ThemeSwitcher. frappe-ui 1.0 marks it `@deprecated` — "Use `Select` with
    `useColorScheme` instead" — and it calls warnDeprecated on every render, so
    the control is assembled here from `useColorScheme` and one of the renderings
    `lib/shell/appearance.js` offers.
  -->
  <SettingsRow
    :title="__('Theme')"
    :description="__('Light, dark, or matching your system.')"
  >
    <!-- All three at once rather than behind a Select. This is a three-state
         preference somebody flips and looks at, the row has the width for it,
         and it is the control the phone's More sheet already draws — one
         setting rendered one way. "Theme" and not "Appearance", which is the
         name of the panel it now sits in and said the same word twice. -->
    <TabButtons v-model="scheme" :options="tabOptions" />
  </SettingsRow>
</template>

<script setup>
import { SettingsRow, TabButtons } from '@/ui'
import { useAppearance } from '@/modules/onespace/lib/shell/appearance'
import { __ } from '@/shared/lib/runtime/translate'

// Three states, not a toggle. A binary switch cannot express 'follow the
// system', so a user who wants that has to keep changing it by hand twice a day.
const { scheme, tabOptions } = useAppearance()
</script>
