<!-- Generated by scripts/gen_frontend.py. Edit that, not this file. -->
<template>
  <div>
    <div class="flex items-baseline justify-between gap-2">
      <span class="text-p-sm text-ink-secondary">{{ label }}</span>
      <span class="shrink-0 text-p-sm tabular-nums" :class="valueClass">
        {{ formatted }}
      </span>
    </div>
    <Progress class="mt-1.5" size="sm" :value="percent" :class="barClass" />
    <!--
      A workspace inside an overage window is over its limit and not blocked,
      and the two things have to be said together. Without this the bar reads
      "At the limit. Free some space" directly under an alert saying nothing is
      blocked, and the customer believes whichever they read second.
    -->
    <p v-if="usage?.exceeded && graceUntil" class="mt-1.5 text-p-sm text-ink-amber-3">
      {{ __('Over the limit, but not blocked until {0}.', [graceUntil]) }}
    </p>
    <p v-else-if="usage?.exceeded" class="mt-1.5 text-p-sm text-ink-red-3">
      {{ exceededHint }}
    </p>
    <p v-else-if="usage?.warn" class="mt-1.5 text-p-sm text-ink-amber-3">
      {{ __('Approaching the limit.') }}
    </p>
  </div>
</template>

<script setup>
import { computed } from 'vue'
import { Progress } from '@/ui'
import { __ } from '@/shared/lib/runtime/translate'

const props = defineProps({
  label: { type: String, required: true },
  usage: { type: Object, default: null },
  // 'bytes' for storage and database, 'count' for seats.
  format: { type: String, default: 'bytes' },
  exceededHint: { type: String, default: () => __('At the limit. Free some space or add more.') },
  // Set while an overage window is open, and it changes what being over means:
  // amber and a date rather than red and an instruction.
  graceUntil: { type: String, default: '' },
})

const percent = computed(() => Math.min((props.usage?.fraction || 0) * 100, 100))

// Progress has no `theme`: its fill is always `bg-surface-gray-10`, so the
// colour has to be applied from outside. `class` falls through to the root, and
// the fill is the element inside `role="progressbar"` — `!` because the
// component's own background class is on that same element.
const barClass = computed(() => {
  if (props.usage?.exceeded && props.graceUntil)
    return '[&_[role=progressbar]>*]:!bg-surface-amber-5'
  if (props.usage?.exceeded) return '[&_[role=progressbar]>*]:!bg-surface-red-6'
  if (props.usage?.warn) return '[&_[role=progressbar]>*]:!bg-surface-amber-5'
  return ''
})

const valueClass = computed(() => {
  if (props.usage?.exceeded && props.graceUntil) return 'text-ink-amber-3'
  if (props.usage?.exceeded) return 'text-ink-red-3'
  if (props.usage?.warn) return 'text-ink-amber-3'
  return 'text-ink-secondary'
})

function bytes(value) {
  if (!value) return '0 B'
  const units = ['B', 'KB', 'MB', 'GB', 'TB']
  const i = Math.min(Math.floor(Math.log(value) / Math.log(1024)), units.length - 1)
  return `${(value / 1024 ** i).toFixed(i === 0 ? 0 : 1)} ${units[i]}`
}

const formatted = computed(() => {
  const u = props.usage
  if (!u) return ''
  if (!u.quota) return props.format === 'bytes' ? bytes(u.used) : String(u.used)
  return props.format === 'bytes'
    ? __('{0} of {1}', [bytes(u.used), bytes(u.quota)])
    : __('{0} of {1}', [u.used, u.quota])
})
</script>
