"""Every Frappe fieldtype, and whether we offer to write it.

Generated by scripts/gen_doctypes.py from scripts/field_types.py. Do not edit:
the browser reads the same table out of `src/lib/fields.js`, and the one thing
worse than the two disagreeing is them disagreeing about `editable` — the form
would offer a control the server then refuses.
"""

# fieldtype -> (control, cell, icon, editable)
FIELD_TYPES = {'Attach': ('FileUploader', 'attachment', 'lucide-paperclip', True),
 'Attach Image': ('FileUploader', 'image', 'lucide-image', True),
 'Autocomplete': ('FormControl:combobox', 'text', 'lucide-text-cursor-input', True),
 'Barcode': (None, 'text', 'lucide-scan-barcode', False),
 'Check': ('Switch', 'check', 'lucide-toggle-left', True),
 'Code': ('FormControl:textarea', 'code', 'lucide-code', True),
 'Color': (None, 'color', 'lucide-palette', False),
 'Currency': ('FormControl:number', 'currency', 'lucide-wallet', True),
 'Data': ('FormControl:text', 'text', 'lucide-type', True),
 'Date': ('FormControl:date', 'date', 'lucide-calendar', True),
 'Datetime': ('FormControl:datetime', 'datetime', 'lucide-calendar-clock', True),
 'Duration': ('Duration', 'duration', 'lucide-timer', True),
 'Dynamic Link': ('Combobox', 'link', 'lucide-link-2', True),
 'Float': ('FormControl:number', 'number', 'lucide-hash', True),
 'Geolocation': (None, 'text', 'lucide-map-pin', False),
 'HTML Editor': ('FormControl:textarea', 'html', 'lucide-code-xml', True),
 'Icon': (None, 'icon', 'lucide-shapes', False),
 'Int': ('FormControl:number', 'number', 'lucide-hash', True),
 'JSON': ('FormControl:textarea', 'code', 'lucide-braces', True),
 'Link': ('Combobox', 'link', 'lucide-link', True),
 'Long Int': ('FormControl:number', 'number', 'lucide-hash', True),
 'Long Text': ('FormControl:textarea', 'text', 'lucide-align-left', True),
 'Markdown Editor': ('FormControl:textarea', 'text', 'lucide-file-text', True),
 'Password': ('Password', 'hidden', 'lucide-key-round', True),
 'Percent': ('FormControl:number', 'percent', 'lucide-percent', True),
 'Phone': ('FormControl:tel', 'text', 'lucide-phone', True),
 'Rating': ('Rating', 'rating', 'lucide-star', True),
 'Read Only': ('FormControl:text', 'text', 'lucide-lock', False),
 'Select': ('FormControl:select', 'badge', 'lucide-list', True),
 'Signature': (None, 'text', 'lucide-signature', False),
 'Slider': ('Slider', 'number', 'lucide-sliders', True),
 'Small Text': ('FormControl:textarea', 'text', 'lucide-align-left', True),
 'Table': (None, 'hidden', 'lucide-table', False),
 'Table MultiSelect': ('MultiSelect', 'tags', 'lucide-tags', True),
 'Text': ('FormControl:textarea', 'text', 'lucide-align-left', True),
 'Text Editor': ('FormControl:textarea', 'html', 'lucide-pilcrow', True),
 'Time': ('FormControl:time', 'time', 'lucide-clock', True)}

LAYOUT_TYPES = ('Section Break',
 'Column Break',
 'Tab Break',
 'HTML',
 'Button',
 'Image',
 'Fold',
 'Heading',
 'Attachment Gallery')

DATA_OPTIONS = {'Barcode': 'text',
 'Email': 'email',
 'IBAN': 'text',
 'Name': 'text',
 'Phone': 'tel',
 'URL': 'url'}

# Frappe's own bookkeeping. Never a column, never a control: a customer editing
# `owner` or `docstatus` is always a mistake.
RESERVED = frozenset({'_assign',
           '_comments',
           '_liked_by',
           '_seen',
           '_user_tags',
           'creation',
           'docstatus',
           'doctype',
           'idx',
           'modified',
           'modified_by',
           'name',
           'naming_series',
           'owner',
           'parent',
           'parentfield',
           'parenttype'})


def editable(fieldtype: str) -> bool:
	"""Whether a field of this type can be offered for editing at all.

	Unknown is not editable. If we do not know what it is, we do not know how to
	write it, and a text box over an unknown type saves the wrong shape.
	"""
	row = FIELD_TYPES.get(fieldtype)
	return bool(row and row[3])


def icon_for(fieldtype: str) -> str:
	return (FIELD_TYPES.get(fieldtype) or (None, None, "lucide-circle-help", False))[2]


def cell_for(fieldtype: str) -> str:
	return (FIELD_TYPES.get(fieldtype) or (None, "text", None, False))[1]
