// Generated by scripts/gen_frontend.py. Edit that, not this file.

/**
 * Every Frappe fieldtype, and what renders it.
 *
 * Generated from scripts/field_types.py, which is checked against Frappe's own
 * `data_fieldtypes` — so a fieldtype Frappe adds fails the build here rather
 * than rendering as a text box that saves a string into a Currency column.
 *
 * `control` is a FormControl type as "FormControl:<type>", or the name of a
 * component in the barrel. `null` means shown but never offered: colour,
 * signature and geolocation have no frappe-ui counterpart, and a control that
 * cannot produce the right shape is worse than none.
 */

export const FIELD_TYPES = {
  "Attach": {
    "cell": "attachment",
    "control": "FileUploader",
    "editable": true,
    "icon": "lucide-paperclip"
  },
  "Attach Image": {
    "cell": "image",
    "control": "FileUploader",
    "editable": true,
    "icon": "lucide-image"
  },
  "Attachment Gallery": {
    "cell": "hidden",
    "control": "AttachmentGallery",
    "editable": false,
    "icon": "lucide-images"
  },
  "Autocomplete": {
    "cell": "text",
    "control": "FormControl:combobox",
    "editable": true,
    "icon": "lucide-text-cursor-input"
  },
  "Barcode": {
    "cell": "text",
    "control": null,
    "editable": false,
    "icon": "lucide-scan-barcode"
  },
  "Check": {
    "cell": "check",
    "control": "Switch",
    "editable": true,
    "icon": "lucide-toggle-left"
  },
  "Code": {
    "cell": "code",
    "control": "CodeEditor",
    "editable": true,
    "icon": "lucide-code"
  },
  "Color": {
    "cell": "color",
    "control": null,
    "editable": false,
    "icon": "lucide-palette"
  },
  "Currency": {
    "cell": "currency",
    "control": "FormControl:number",
    "editable": true,
    "icon": "lucide-wallet"
  },
  "Data": {
    "cell": "text",
    "control": "FormControl:text",
    "editable": true,
    "icon": "lucide-type"
  },
  "Date": {
    "cell": "date",
    "control": "FormControl:date",
    "editable": true,
    "icon": "lucide-calendar"
  },
  "Datetime": {
    "cell": "datetime",
    "control": "FormControl:datetime",
    "editable": true,
    "icon": "lucide-calendar-clock"
  },
  "Duration": {
    "cell": "duration",
    "control": "Duration",
    "editable": true,
    "icon": "lucide-timer"
  },
  "Dynamic Link": {
    "cell": "link",
    "control": "Combobox",
    "editable": true,
    "icon": "lucide-link-2"
  },
  "Float": {
    "cell": "number",
    "control": "FormControl:number",
    "editable": true,
    "icon": "lucide-hash"
  },
  "Geolocation": {
    "cell": "text",
    "control": null,
    "editable": false,
    "icon": "lucide-map-pin"
  },
  "HTML Editor": {
    "cell": "html",
    "control": "CodeEditor",
    "editable": true,
    "icon": "lucide-code-xml"
  },
  "Icon": {
    "cell": "icon",
    "control": null,
    "editable": false,
    "icon": "lucide-shapes"
  },
  "Int": {
    "cell": "number",
    "control": "FormControl:number",
    "editable": true,
    "icon": "lucide-hash"
  },
  "JSON": {
    "cell": "code",
    "control": "CodeEditor",
    "editable": true,
    "icon": "lucide-braces"
  },
  "Link": {
    "cell": "link",
    "control": "Combobox",
    "editable": true,
    "icon": "lucide-link"
  },
  "Long Int": {
    "cell": "number",
    "control": "FormControl:number",
    "editable": true,
    "icon": "lucide-hash"
  },
  "Long Text": {
    "cell": "text",
    "control": "FormControl:textarea",
    "editable": true,
    "icon": "lucide-align-left"
  },
  "Markdown Editor": {
    "cell": "text",
    "control": "Editor:markdown",
    "editable": true,
    "icon": "lucide-file-text"
  },
  "Password": {
    "cell": "hidden",
    "control": "Password",
    "editable": true,
    "icon": "lucide-key-round"
  },
  "Percent": {
    "cell": "percent",
    "control": "FormControl:number",
    "editable": true,
    "icon": "lucide-percent"
  },
  "Phone": {
    "cell": "text",
    "control": "FormControl:tel",
    "editable": true,
    "icon": "lucide-phone"
  },
  "Rating": {
    "cell": "rating",
    "control": "Rating",
    "editable": true,
    "icon": "lucide-star"
  },
  "Read Only": {
    "cell": "text",
    "control": "FormControl:text",
    "editable": false,
    "icon": "lucide-lock"
  },
  "Select": {
    "cell": "badge",
    "control": "FormControl:select",
    "editable": true,
    "icon": "lucide-list"
  },
  "Signature": {
    "cell": "text",
    "control": null,
    "editable": false,
    "icon": "lucide-signature"
  },
  "Slider": {
    "cell": "number",
    "control": "Slider",
    "editable": true,
    "icon": "lucide-sliders"
  },
  "Small Text": {
    "cell": "text",
    "control": "FormControl:textarea",
    "editable": true,
    "icon": "lucide-align-left"
  },
  "Table": {
    "cell": "hidden",
    "control": null,
    "editable": false,
    "icon": "lucide-table"
  },
  "Table MultiSelect": {
    "cell": "tags",
    "control": "MultiSelect",
    "editable": true,
    "icon": "lucide-tags"
  },
  "Text": {
    "cell": "text",
    "control": "FormControl:textarea",
    "editable": true,
    "icon": "lucide-align-left"
  },
  "Text Editor": {
    "cell": "html",
    "control": "Editor:html",
    "editable": true,
    "icon": "lucide-pilcrow"
  },
  "Time": {
    "cell": "time",
    "control": "FormControl:time",
    "editable": true,
    "icon": "lucide-clock"
  }
}

/** Layout fields. They carry no value and are skipped rather than rendered. */
export const LAYOUT_TYPES = [
  "Section Break",
  "Column Break",
  "Tab Break",
  "HTML",
  "Button",
  "Image",
  "Fold",
  "Heading"
]

/** What `options` on a Data field refines the input to. Frappe's own list. */
export const DATA_OPTIONS = {
  "Barcode": "text",
  "Email": "email",
  "IBAN": "text",
  "Name": "text",
  "Phone": "tel",
  "URL": "url"
}

/**
 * Cells whose value is a number, and so sits against the right edge.
 *
 * By cell rather than by fieldtype: the cell is what already decides how a
 * value is drawn, so a Currency and an Int are one question here, and a
 * fieldtype added to the map lands in a bucket without a second list to
 * remember.
 */
export const NUMERIC_CELLS = [
  "number",
  "currency",
  "percent"
]

export function isNumericCell(cell) {
  return NUMERIC_CELLS.includes(cell)
}

/** DocType State's palette, in Badge themes. */
export const STATE_COLORS = {
  "Blue": "blue",
  "Cyan": "teal",
  "Gray": "gray",
  "Green": "green",
  "Light Blue": "blue",
  "Orange": "orange",
  "Pink": "pink",
  "Purple": "violet",
  "Red": "red",
  "Yellow": "amber"
}

/** Frappe's own word lists, so a status reads the same colour as in the desk. */
const WORD_COLORS = [
  [
    "amber",
    [
      "pending",
      "review",
      "medium",
      "not approved",
      "draft",
      "queued"
    ]
  ],
  [
    "red",
    [
      "open",
      "urgent",
      "high",
      "failed",
      "rejected",
      "error",
      "cancelled",
      "overdue",
      "expired"
    ]
  ],
  [
    "green",
    [
      "closed",
      "finished",
      "converted",
      "completed",
      "complete",
      "confirmed",
      "approved",
      "yes",
      "active",
      "available",
      "paid",
      "success"
    ]
  ],
  [
    "blue",
    [
      "submitted",
      "in progress",
      "working",
      "scheduled"
    ]
  ]
]

/**
 * The glyphs a status may carry, written as literals so Tailwind emits them.
 *
 * A second closed set beside SPACE_ICONS, closed for the same reason and
 * answering a different question: those say what an app *is*, these say where a
 * record *stands*.
 */
export const STATE_ICONS = [
  "lucide-circle-check",
  "lucide-circle-dashed",
  "lucide-circle-dot",
  "lucide-loader",
  "lucide-clock",
  "lucide-triangle-alert",
  "lucide-circle-x",
  "lucide-circle-pause",
  "lucide-archive",
  "lucide-trash-2",
  "lucide-arrow-down-left",
  "lucide-arrow-up-right",
  "lucide-tag"
]

/** Which glyph a state's own words earn, in order — first match wins. */
const STATE_ICON_WORDS = [
  [
    "lucide-circle-x",
    [
      "failed",
      "broken",
      "cancelled",
      "canceled",
      "refused",
      "rejected",
      "lost",
      "abandoned"
    ]
  ],
  [
    "lucide-trash-2",
    [
      "purged",
      "deleted",
      "destroyed"
    ]
  ],
  [
    "lucide-archive",
    [
      "archived",
      "retired",
      "withdrawn",
      "expired",
      "closed",
      "deprecated",
      "released",
      "ignored"
    ]
  ],
  [
    "lucide-circle-pause",
    [
      "suspended",
      "paused",
      "held",
      "on hold",
      "draining",
      "maintenance",
      "past due",
      "overdue",
      "blocked"
    ]
  ],
  [
    "lucide-triangle-alert",
    [
      "warned",
      "review",
      "over",
      "full",
      "attention",
      "incomplete",
      "unpaid"
    ]
  ],
  [
    "lucide-loader",
    [
      "provisioning",
      "running",
      "creating",
      "bootstrapping",
      "restoring",
      "syncing",
      "processing",
      "pending"
    ]
  ],
  [
    "lucide-clock",
    [
      "requested",
      "awaiting",
      "queued",
      "scheduled",
      "trialing",
      "trial",
      "received",
      "preview"
    ]
  ],
  [
    "lucide-circle-check",
    [
      "active",
      "succeeded",
      "success",
      "completed",
      "complete",
      "done",
      "paid",
      "ready",
      "available",
      "processed",
      "committed",
      "claimed",
      "resumed",
      "cleared",
      "taken",
      "restored",
      "granted"
    ]
  ],
  [
    "lucide-circle-dot",
    [
      "open",
      "draft",
      "new"
    ]
  ],
  [
    "lucide-arrow-down-left",
    [
      "grant",
      "purchase",
      "refund",
      "credit"
    ]
  ],
  [
    "lucide-arrow-up-right",
    [
      "spend",
      "charge",
      "debit"
    ]
  ]
]

/**
 * The icon for one value of a status Select.
 *
 * Derived from the words rather than declared, because the alternative is
 * typing an icon name beside all fifty-odd options and the words already say
 * it — `Failed` and `Broken` mean the same thing to a reader and should not
 * need two decisions. A doctype that disagrees declares its own, and that
 * override arrives on the state itself.
 *
 * Never nothing: a Select shown as a badge is a category even where it is not a
 * status, and a row where half the badges carry an icon reads as broken rather
 * than as varied. Those get the neutral tag.
 */
export function valueIcon(value, states = []) {
  if (!value) return ''

  const declared = states.find((s) => s.title === value)
  if (declared?.icon) return declared.icon

  const text = String(value).toLowerCase()
  for (const [icon, words] of STATE_ICON_WORDS) {
    if (words.some((word) => text.includes(word))) return icon
  }
  return 'lucide-tag'
}

/**
 * The glyphs a tab may carry, written as literals so Tailwind emits them.
 *
 * A third closed set, for the same build-time reason as the other two. Frappe
 * has no icon property on a Tab Break — a doctype's tabs are a label and
 * nothing else — so this is how a form laid out by somebody who never heard of
 * OneSpace still gets a strip of tabs that reads as one.
 */
export const TAB_ICONS = [
  "lucide-list",
  "lucide-link",
  "lucide-info",
  "lucide-sticky-note",
  "lucide-message-circle",
  "lucide-history",
  "lucide-activity",
  "lucide-paperclip",
  "lucide-settings",
  "lucide-shield",
  "lucide-users",
  "lucide-map-pin",
  "lucide-calculator",
  "lucide-banknote",
  "lucide-calendar",
  "lucide-package",
  "lucide-file-text",
  "lucide-mail",
  "lucide-bell",
  "lucide-plug",
  "lucide-ruler",
  "lucide-panel-top"
]

/** Which glyph a tab's own words earn, in order — first match wins. */
const TAB_ICON_WORDS = [
  [
    "lucide-link",
    [
      "connection",
      "link",
      "related",
      "reference"
    ]
  ],
  [
    "lucide-history",
    [
      "history",
      "changes",
      "audit",
      "log",
      "version",
      "revision"
    ]
  ],
  [
    "lucide-activity",
    [
      "activity",
      "timeline",
      "event"
    ]
  ],
  [
    "lucide-message-circle",
    [
      "comment",
      "discussion",
      "feedback",
      "reply"
    ]
  ],
  [
    "lucide-paperclip",
    [
      "file",
      "attachment",
      "document",
      "upload"
    ]
  ],
  [
    "lucide-shield",
    [
      "permission",
      "role",
      "access",
      "security",
      "sharing"
    ]
  ],
  [
    "lucide-bell",
    [
      "notification",
      "alert",
      "reminder",
      "subscriber"
    ]
  ],
  [
    "lucide-mail",
    [
      "email",
      "mail",
      "inbox",
      "message"
    ]
  ],
  [
    "lucide-plug",
    [
      "integration",
      "api",
      "webhook",
      "connector",
      "sync"
    ]
  ],
  [
    "lucide-banknote",
    [
      "payment",
      "pricing",
      "price",
      "billing",
      "currency",
      "invoice",
      "credit",
      "cost",
      "rate",
      "amount",
      "commission",
      "discount"
    ]
  ],
  [
    "lucide-calculator",
    [
      "accounting",
      "account",
      "tax",
      "total",
      "charge",
      "ledger"
    ]
  ],
  [
    "lucide-package",
    [
      "item",
      "product",
      "stock",
      "inventory",
      "material",
      "warehouse",
      "delivery",
      "shipping"
    ]
  ],
  [
    "lucide-map-pin",
    [
      "address",
      "location",
      "region",
      "territory"
    ]
  ],
  [
    "lucide-users",
    [
      "contact",
      "people",
      "member",
      "team",
      "user",
      "party",
      "participant",
      "attendee",
      "guest",
      "customer",
      "supplier",
      "employee",
      "assign"
    ]
  ],
  [
    "lucide-calendar",
    [
      "date",
      "schedule",
      "timing",
      "period"
    ]
  ],
  [
    "lucide-ruler",
    [
      "dimension",
      "measurement",
      "size",
      "weight"
    ]
  ],
  [
    "lucide-sticky-note",
    [
      "note",
      "remark",
      "description",
      "summary"
    ]
  ],
  [
    "lucide-settings",
    [
      "setting",
      "preference",
      "configuration",
      "option",
      "advanced",
      "rule"
    ]
  ],
  [
    "lucide-info",
    [
      "information",
      "about",
      "misc",
      "other"
    ]
  ],
  [
    "lucide-file-text",
    [
      "print",
      "template",
      "content",
      "text",
      "letter",
      "legal",
      "term",
      "condition"
    ]
  ],
  [
    "lucide-list",
    [
      "detail",
      "general",
      "overview",
      "main",
      "basic",
      "primary"
    ]
  ]
]

const DEFAULT_TAB_ICON = 'lucide-panel-top'

/**
 * The icon for one tab, by its label.
 *
 * `declared` is a manifest's override, keyed by the tab's label — the escape
 * hatch for a tab whose words say nothing useful. Checked against the closed
 * set rather than trusted: a name outside it emits no CSS and draws a blank,
 * which is worse than the derived glyph it replaced.
 *
 * Never nothing. A strip where three tabs carry an icon and the fourth does
 * not reads as a tab that failed to load.
 */
export function tabIcon(label, declared = null) {
  const override = declared?.[label]
  if (override && TAB_ICONS.includes(override)) return override

  const text = String(label || '').trim().toLowerCase()
  for (const [icon, words] of TAB_ICON_WORDS) {
    if (words.some((word) => text.includes(word))) return icon
  }
  return DEFAULT_TAB_ICON
}

/**
 * The glyphs a timeline entry may carry, written as literals so Tailwind emits
 * them.
 *
 * The fourth closed set. One timeline over a record means a comment and a
 * field change sit in the same column, and a column of identical avatars makes
 * two different events look like one.
 */
export const ACTIVITY_ICONS = {
  "change": "lucide-pencil",
  "comment": "lucide-message-circle",
  "created": "lucide-circle-plus"
}

const DEFAULT_ACTIVITY_ICON = 'lucide-dot'

/** The glyph for one kind of timeline entry. */
export function activityIcon(kind) {
  return ACTIVITY_ICONS[kind] || DEFAULT_ACTIVITY_ICON
}

// Named rather than counted. Stripping this with a hand-written offset is how
// every FormControl type lost its first letter — "date" became "ate", which is
// not in the union, and FormControl answers an unknown type with a plain text
// box and no warning. So the whole record dialog rendered as text inputs and
// nothing anywhere said so.
const FORM_CONTROL = 'FormControl:'

const FALLBACK = {
  control: FORM_CONTROL + 'text',
  cell: 'text',
  icon: 'lucide-circle-help',
  editable: false,
}

/**
 * How to render one field.
 *
 * An unknown fieldtype falls back to a read-only text cell rather than to an
 * editable one: if we do not know what it is, we do not know how to write it.
 */
export function fieldSpec(field) {
  const base = FIELD_TYPES[field?.fieldtype] || FALLBACK

  // `options` on a Data field says what it really holds — an email, a URL, a
  // phone number — and the browser has better keyboards and validation for
  // each than it does for "text".
  if (field?.fieldtype === 'Data' && DATA_OPTIONS[field.options]) {
    return { ...base, control: FORM_CONTROL + DATA_OPTIONS[field.options] }
  }
  return base
}

// The prose editor, and the format it round-trips. Frappe's Text Editor and
// Markdown Editor are the same component storing different text, so the table
// names both as `Editor:<format>` rather than as two components that do not
// exist.
const EDITOR = 'Editor:'

/** The FormControl `type`, or null when this field needs a named component. */
export function formControlType(field) {
  const { control } = fieldSpec(field)
  return control && control.startsWith(FORM_CONTROL) ? control.slice(FORM_CONTROL.length) : null
}

/** The component name, or null when a FormControl handles it. */
export function controlComponent(field) {
  const { control } = fieldSpec(field)
  if (!control || control.startsWith(FORM_CONTROL)) return null
  return control.startsWith(EDITOR) ? 'Editor' : control
}

/**
 * The Editor's `format`, or null for every field that is not one.
 *
 * Named rather than sliced at the call site for the reason the FORM_CONTROL
 * comment above gives: a hand-written offset is how every control type once
 * lost its first letter, and an Editor handed a format it does not know
 * renders an empty document rather than complaining.
 */
export function editorFormat(field) {
  const { control } = fieldSpec(field)
  return control && control.startsWith(EDITOR) ? control.slice(EDITOR.length) : null
}

/**
 * Filter operators, ported from Frappe's own filter UI.
 *
 * Frappe writes this as a deny list per fieldtype (`invalid_condition_map`);
 * it is inverted into an allow list here and generated into the server module
 * too, so the menu a person sees and the check the server makes are the same
 * table. `tests/test_field_types.py` reads Frappe's `filter.js` back and fails
 * when the two drift.
 */
export const OPERATORS = {
  "=": "Equals",
  "!=": "Not Equals",
  "like": "Like",
  "not like": "Not Like",
  "in": "In",
  "not in": "Not In",
  "is": "Is",
  ">": "Greater Than",
  "<": "Less Than",
  ">=": "Greater Than Or Equal To",
  "<=": "Less Than Or Equal To",
  "between": "Between",
  "timespan": "Timespan"
}

/** Frappe relabels the comparisons for a date: "Before" reads better than "<". */
export const OPERATOR_LABELS_BY_TYPE = {
  "Date": {
    "<": "Before",
    ">": "After",
    "<=": "On or Before",
    ">=": "On or After"
  },
  "Datetime": {
    "<": "Before",
    ">": "After",
    "<=": "On or Before",
    ">=": "On or After"
  }
}

const VALID_OPERATORS = {
  "Attach": [
    "=",
    "!=",
    "like",
    "not like",
    "in",
    "not in",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ],
  "Attach Image": [
    "=",
    "!=",
    "like",
    "not like",
    "in",
    "not in",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ],
  "Attachment Gallery": [
    "=",
    "!=",
    "is"
  ],
  "Autocomplete": [
    "=",
    "!=",
    "like",
    "not like",
    "in",
    "not in",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ],
  "Barcode": [
    "=",
    "!=",
    "like",
    "not like",
    "in",
    "not in",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ],
  "Check": [
    "="
  ],
  "Code": [
    "=",
    "!=",
    "like",
    "not like",
    "is"
  ],
  "Color": [
    "=",
    "!=",
    "like",
    "not like",
    "in",
    "not in",
    "is"
  ],
  "Currency": [
    "=",
    "!=",
    "like",
    "not like",
    "in",
    "not in",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ],
  "Data": [
    "=",
    "!=",
    "like",
    "not like",
    "in",
    "not in",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ],
  "Date": [
    "=",
    "!=",
    "in",
    "not in",
    "is",
    ">",
    "<",
    ">=",
    "<=",
    "between",
    "timespan"
  ],
  "Datetime": [
    "is",
    ">",
    "<",
    ">=",
    "<=",
    "between",
    "timespan"
  ],
  "Duration": [
    "=",
    "!=",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ],
  "Dynamic Link": [
    "=",
    "!=",
    "like",
    "not like",
    "in",
    "not in",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ],
  "Float": [
    "=",
    "!=",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ],
  "Geolocation": [
    "=",
    "!=",
    "is"
  ],
  "HTML Editor": [
    "=",
    "!=",
    "like",
    "not like",
    "is"
  ],
  "Icon": [
    "=",
    "!=",
    "is"
  ],
  "Int": [
    "=",
    "!=",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ],
  "JSON": [
    "=",
    "!=",
    "like",
    "not like",
    "in",
    "not in",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ],
  "Link": [
    "=",
    "!=",
    "like",
    "not like",
    "in",
    "not in",
    "is"
  ],
  "Long Int": [
    "=",
    "!=",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ],
  "Long Text": [
    "=",
    "!=",
    "like",
    "not like",
    "is"
  ],
  "Markdown Editor": [
    "=",
    "!=",
    "like",
    "not like",
    "is"
  ],
  "Password": [
    "=",
    "!=",
    "like",
    "not like",
    "is"
  ],
  "Percent": [
    "=",
    "!=",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ],
  "Phone": [
    "=",
    "!=",
    "like",
    "not like",
    "in",
    "not in",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ],
  "Rating": [
    "=",
    "!=",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ],
  "Read Only": [
    "=",
    "!=",
    "like",
    "not like",
    "in",
    "not in",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ],
  "Select": [
    "=",
    "!=",
    "in",
    "not in",
    "is"
  ],
  "Signature": [
    "=",
    "!=",
    "is"
  ],
  "Slider": [
    "=",
    "!=",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ],
  "Small Text": [
    "=",
    "!=",
    "like",
    "not like",
    "is"
  ],
  "Table": [],
  "Table MultiSelect": [],
  "Text": [
    "=",
    "!=",
    "like",
    "not like",
    "is"
  ],
  "Text Editor": [
    "=",
    "!=",
    "like",
    "not like",
    "is"
  ],
  "Time": [
    "=",
    "!=",
    "like",
    "not like",
    "in",
    "not in",
    "is",
    ">",
    "<",
    ">=",
    "<="
  ]
}

/** Frappe's relative-date vocabulary, in its order. */
export const TIMESPANS = [
  {
    "value": "last 7 days",
    "label": "Last 7 Days"
  },
  {
    "value": "last 14 days",
    "label": "Last 14 Days"
  },
  {
    "value": "last 30 days",
    "label": "Last 30 Days"
  },
  {
    "value": "last 90 days",
    "label": "Last 90 Days"
  },
  {
    "value": "last week",
    "label": "Last Week"
  },
  {
    "value": "last month",
    "label": "Last Month"
  },
  {
    "value": "last quarter",
    "label": "Last Quarter"
  },
  {
    "value": "last 6 months",
    "label": "Last 6 Months"
  },
  {
    "value": "last year",
    "label": "Last Year"
  },
  {
    "value": "yesterday",
    "label": "Yesterday"
  },
  {
    "value": "today",
    "label": "Today"
  },
  {
    "value": "tomorrow",
    "label": "Tomorrow"
  },
  {
    "value": "this week",
    "label": "This Week"
  },
  {
    "value": "this month",
    "label": "This Month"
  },
  {
    "value": "this quarter",
    "label": "This Quarter"
  },
  {
    "value": "this year",
    "label": "This Year"
  },
  {
    "value": "next 7 days",
    "label": "Next 7 Days"
  },
  {
    "value": "next 14 days",
    "label": "Next 14 Days"
  },
  {
    "value": "next 30 days",
    "label": "Next 30 Days"
  },
  {
    "value": "next week",
    "label": "Next Week"
  },
  {
    "value": "next month",
    "label": "Next Month"
  },
  {
    "value": "next quarter",
    "label": "Next Quarter"
  },
  {
    "value": "next 6 months",
    "label": "Next 6 Months"
  },
  {
    "value": "next year",
    "label": "Next Year"
  }
]

const DEFAULT_OPERATORS = {
  "Attach": "like",
  "Attach Image": "like",
  "Attachment Gallery": "=",
  "Autocomplete": "like",
  "Barcode": "like",
  "Check": "=",
  "Code": "like",
  "Color": "=",
  "Currency": "=",
  "Data": "like",
  "Date": "between",
  "Datetime": "between",
  "Duration": "=",
  "Dynamic Link": "like",
  "Float": "=",
  "Geolocation": "=",
  "HTML Editor": "like",
  "Icon": "=",
  "Int": "=",
  "JSON": "like",
  "Link": "=",
  "Long Int": "=",
  "Long Text": "like",
  "Markdown Editor": "like",
  "Password": "like",
  "Percent": "=",
  "Phone": "like",
  "Rating": "=",
  "Read Only": "like",
  "Select": "=",
  "Signature": "=",
  "Slider": "=",
  "Small Text": "like",
  "Table": "",
  "Table MultiSelect": "",
  "Text": "like",
  "Text Editor": "like",
  "Time": "="
}

const EQUALITY = ['=', '!=']
const IN = ['in', 'not in']

/** Which operators a filter on this field may use. */
export function operatorsFor(field) {
  return VALID_OPERATORS[field?.fieldtype] || ['=', '!=', 'is']
}

/** What an operator is called on this field. */
export function operatorLabel(field, operator) {
  return OPERATOR_LABELS_BY_TYPE[field?.fieldtype]?.[operator] || OPERATORS[operator] || operator
}

/** What a filter opens on: a substring for text, a range for a date. */
export function defaultOperator(field) {
  // Stored as a JSON array, so an exact match can never hit.
  if (['_assign', '_liked_by'].includes(field?.fieldname)) return 'like'
  return DEFAULT_OPERATORS[field?.fieldtype] || '='
}

/**
 * What the value control has to be, once the operator is known.
 *
 * Frappe does this by rewriting the docfield in `set_fieldtype`. Naming the
 * decision instead means the server can check a value without rendering one,
 * which is why this same function exists on both sides.
 */
export function valueShape(field, operator) {
  if (operator === 'is') return 'set'
  if (operator === 'timespan') return 'timespan'
  if (operator === 'between') return 'range'
  if (IN.includes(operator)) return 'multi'
  const fieldtype = field?.fieldtype
  if (fieldtype === 'Check' || fieldtype === 'Select') return 'choice'
  if (['Link', 'Dynamic Link'].includes(fieldtype) && EQUALITY.includes(operator)) return 'link'
  // Everything else is a plain box, a Link under `like` included: matching part
  // of a name is a text question.
  return 'value'
}

/** Set / Not Set, which is what `is` asks. */
export const IS_OPTIONS = [
  { value: 'set', label: 'Set' },
  { value: 'not set', label: 'Not Set' },
]

/** A checkbox is one of two things, and neither of them is a text box. */
export const CHECK_OPTIONS = [
  { value: '1', label: 'Yes' },
  { value: '0', label: 'No' },
]

export function isLayout(fieldtype) {
  return LAYOUT_TYPES.includes(fieldtype)
}

/**
 * The Badge theme for a value.
 *
 * The doctype's own `states` first — Frappe stores a colour per status right on
 * the doctype, so a badge is coloured by what the doctype declares rather than
 * by anything guessed here. Only then the word lists, which are Frappe's, so a
 * status that has no declared colour still reads the same as it does in the
 * desk. Then gray, which is an answer rather than a failure.
 */
export function valueTheme(value, states = []) {
  if (!value) return 'gray'

  const declared = states.find((s) => s.title === value)
  if (declared) return STATE_COLORS[declared.color] || 'gray'

  const text = String(value).toLowerCase()
  for (const [theme, words] of WORD_COLORS) {
    if (words.some((word) => text.includes(word))) return theme
  }
  return 'gray'
}
